import type { Card, AnnualMilestone, MonthlyMilestone } from "./types";

export const CARDS: readonly Card[] = [
  {
    id: "amex_gold",
    name: "American Express Gold Charge Card",
    short: "Amex Gold",
    network: "Amex",
    issuer: "American Express",
    creditLimit: 0,
    annualFee: 5310,
    feeWaivable: false,
    forexPct: 3.5,
    loungeRule: "—",
    status: "active",
    pointValue: 0.58,
    baseRatePct: 0.78,
    bestRatePct: 5.8,
    statementDay: 28,
  },
  {
    id: "amex_plat_travel",
    name: "American Express Platinum Travel",
    short: "Amex PT",
    network: "Amex",
    issuer: "American Express",
    creditLimit: 1020000,
    annualFee: 5900,
    feeWaivable: false,
    forexPct: 3.5,
    loungeRule: "8/yr domestic + Priority Pass",
    status: "active",
    pointValue: 0.5,
    baseRatePct: 1.0,
    bestRatePct: 7.0,
    cycleEnd: "2026-12-03",
    statementDay: 28,
  },
  {
    id: "amex_mrcc",
    name: "American Express Membership Rewards",
    short: "Amex MRCC",
    network: "Amex",
    issuer: "American Express",
    creditLimit: 470000,
    annualFee: 5310,
    feeWaivable: true,
    feeWaiverAt: 150000,
    forexPct: 3.5,
    loungeRule: "—",
    status: "active",
    pointValue: 0.58,
    baseRatePct: 0.78,
    bestRatePct: 4.7,
    cycleEnd: "2026-11-27",
    statementDay: 28,
  },
  {
    id: "scapia",
    name: "Scapia Federal",
    short: "Scapia",
    network: "Visa Signature",
    issuer: "Federal Bank",
    creditLimit: 404000,
    annualFee: 0,
    feeWaivable: false,
    forexPct: 0,
    loungeRule: "Unlimited (₹20K/mo)",
    status: "active",
    pointValue: 0.2,
    baseRatePct: 2.0,
    bestRatePct: 4.0,
    statementDay: 24,
    notes: "LTF, Visa variant (you don't hold the RuPay one). 10% coins (=2% value) on all eligible spends; 20% coins (=4%) on Scapia-app travel. 5 coins = ₹1, redeemable ONLY for travel on Scapia app/store (not cashable). 0% forex. Excludes: rent, forex, insurance, utility, wallet, education, gift cards, EMI, cash, government, fuel.",
  },
  {
    id: "idfc_indigo",
    name: "IndiGo IDFC FIRST Dual",
    short: "IDFC Indigo",
    network: "Mastercard + RuPay",
    issuer: "IDFC FIRST Bank",
    creditLimit: 220000,
    annualFee: 5900,
    feeWaivable: false,
    forexPct: 1.49,
    loungeRule: "Golf 12 rounds/yr",
    status: "active",
    pointValue: 0.45,
    baseRatePct: 1.35,
    bestRatePct: 9.9,
    statementDay: 22,
    notes: "Dual: Mastercard (1.49% forex) + RuPay (UPI). BluChips/₹100: up to 22 on IndiGo flights via IndiGo site/app (6 card + up to 16 IndiGo tier); 3 on other spends; 0.5 on UPI; 0.5 on insurance/utilities/fuel/rent/wallet. None on cash/EMI. BluChip value dynamic ₹0.40–0.60 (≈₹0.45), redeemable only on IndiGo one-way flights (base fare+fuel), min 500, 24-mo validity. Milestone bonus BluChip vouchers on spends.",
  },
  {
    id: "bob_eterna",
    name: "BOBCARD Eterna",
    short: "BOB Eterna",
    network: "Visa Infinite",
    issuer: "Bank of Baroda",
    creditLimit: 200000,
    annualFee: 0,
    feeWaivable: false,
    forexPct: 2.0,
    loungeRule: "Unlimited (₹40K/qtr)",
    status: "active",
    pointValue: 0.25,
    baseRatePct: 0.75,
    bestRatePct: 3.75,
    statementDay: 13,
    notes: "LTF — you pay ₹0 joining & ₹0 annual. 5X (15 RP/₹100 = 3.75%) on dining, travel, online shopping & international; base 3 RP/₹100 (0.75%); 5X cap 5,000 RP/cycle (~₹33K). Welcome: 10,000 RP @ ₹50K/60d + 6-mo FITPASS Pro (~₹15K). Annual: 20,000 RP @ ₹5L/yr. RP never expire. Telecom (4814) earns base RP from 1 Apr 2026, utility (4900) from 1 Jul 2025. No RP on fuel. District BOGO ₹250/mo.",
  },
  {
    id: "yes_kiwi",
    name: "YES Bank Kiwi Neon",
    short: "YES Bank Neon",
    network: "RuPay",
    issuer: "YES Bank",
    creditLimit: 750000,
    annualFee: 1179,
    feeWaivable: false,
    forexPct: 3.5,
    loungeRule: "Up to 3/yr (Neon milestones)",
    status: "active",
    pointValue: 1.0,
    baseRatePct: 0.25,
    bestRatePct: 5.0,
    notes: "Neon cycle Apr 1 → Mar 31",
    statementDay: 16,
  },
  {
    id: "sbi_simplyclick",
    name: "SBI SimplyCLICK",
    short: "SBI SimplyCLICK",
    network: "Visa Platinum",
    issuer: "SBI Card",
    creditLimit: 240000,
    annualFee: 589,
    feeWaivable: true,
    feeWaiverAt: 100000,
    forexPct: 3.5,
    loungeRule: "—",
    status: "active",
    pointValue: 0.2,
    baseRatePct: 0.25,
    bestRatePct: 2.5,
    statementDay: 21,
  },
  {
    id: "amazon_pay_icici",
    name: "Amazon Pay ICICI Bank",
    short: "Amazon Pay ICICI",
    network: "Visa Platinum",
    issuer: "ICICI Bank",
    creditLimit: 120000,
    annualFee: 0,
    feeWaivable: false,
    forexPct: 1.99,
    loungeRule: "—",
    status: "active",
    pointValue: 1.0,
    baseRatePct: 1.0,
    bestRatePct: 5.0,
    notes: "LTF. 5% Prime / 3% non-Prime on Amazon.in; 2% bills/recharges via Amazon; 1% else. Cashback as Amazon Pay balance.",
  },
  {
    id: "hsbc_live_plus",
    name: "HSBC Live+",
    short: "HSBC Live+",
    network: "Visa Infinite",
    issuer: "HSBC",
    creditLimit: 0,
    annualFee: 1179, // ₹999 + GST approx
    feeWaivable: true,
    feeWaiverAt: 200000,
    forexPct: 1.99,
    loungeRule: "2 domestic/yr + 1 international/yr (from Sep 2026)",
    status: "active",
    pointValue: 1.0,
    baseRatePct: 1.5,
    bestRatePct: 10.0,
    statementDay: 1,
    notes: "ACTIVE — Visa Infinite (from 26 Jul 2026). 10% statement cashback (auto ~45 days) on dining, food delivery, groceries, utilities & shopping; Amazon/Flipkart/Myntra = 1.5% only. Shared accel cap ₹1,200/mo (~₹12k spend). Hospital/local transport = 0%. Welcome: ₹1k CB @ ₹20k/30d + app login. Perks: Times Prime, District BOGO/dining, 2 domestic lounges/yr, 1 intl lounge/yr (from Sep 2026), ~₹250/qtr contactless fuel CB (≥₹10k), Visa Infinite concierge. Forex 1.99%. Fee ₹999+GST, waived at ₹2L/yr.",
  },
];

export const ANNUAL_MILESTONES: readonly AnnualMilestone[] = [
  { cardId: "amex_plat_travel", threshold: 190000, reward: "7,500 MR", rewardValueInr: 3750, hit: true, notes: "Hit earlier this cycle" },
  { cardId: "amex_plat_travel", threshold: 400000, reward: "10,000 MR", rewardValueInr: 5000, hit: false },
  { cardId: "amex_plat_travel", threshold: 700000, reward: "22,500 MR + Taj ₹10K voucher", rewardValueInr: 21250, hit: false },
  { cardId: "amex_mrcc", threshold: 90000, reward: "50% renewal-fee waiver", rewardValueInr: 2655, hit: false },
  { cardId: "amex_mrcc", threshold: 150000, reward: "100% renewal-fee waiver", rewardValueInr: 5310, hit: false },
  { cardId: "sbi_simplyclick", threshold: 100000, reward: "₹2K voucher + fee waiver", rewardValueInr: 2499, hit: false },
  { cardId: "sbi_simplyclick", threshold: 200000, reward: "Additional ₹2K voucher", rewardValueInr: 2000, hit: false },
  { cardId: "idfc_indigo", threshold: 200000, reward: "5,000 BluChips voucher", rewardValueInr: 650, hit: true },
  { cardId: "idfc_indigo", threshold: 500000, reward: "5,000 BluChips voucher", rewardValueInr: 650, hit: true },
  { cardId: "idfc_indigo", threshold: 800000, reward: "5,000 BluChips voucher", rewardValueInr: 650, hit: false },
  { cardId: "idfc_indigo", threshold: 1000000, reward: "5,000 BluChips voucher", rewardValueInr: 650, hit: false },
  { cardId: "idfc_indigo", threshold: 1200000, reward: "5,000 BluChips voucher", rewardValueInr: 650, hit: false },
  { cardId: "bob_eterna", threshold: 50000, reward: "10,000 RP (welcome, 60-day)", rewardValueInr: 2500, hit: false },
  { cardId: "bob_eterna", threshold: 500000, reward: "20,000 RP (annual)", rewardValueInr: 5000, hit: false },
  { cardId: "hsbc_live_plus", threshold: 20000, reward: "₹1,000 welcome cashback (30-day + app login)", rewardValueInr: 1000, hit: false },
  { cardId: "hsbc_live_plus", threshold: 200000, reward: "Annual fee waived (₹999+GST)", rewardValueInr: 1179, hit: false },
];

export const MONTHLY_MILESTONES: readonly MonthlyMilestone[] = [
  { cardId: "amex_gold", rule: "6 transactions ≥₹1,000 in calendar month", rewardMr: 1000, rewardInr: 580, minSpend: 6000 },
  { cardId: "amex_mrcc", rule: "4 transactions ≥₹1,500 in calendar month", rewardMr: 1000, rewardInr: 580, minSpend: 6000 },
  { cardId: "amex_mrcc", rule: "₹20,000 total in calendar month (enrolled)", rewardMr: 1000, rewardInr: 580, minSpend: 20000 },
  { cardId: "scapia", rule: "≥₹20,000 combined V+R for lounge unlock", rewardMr: 0, rewardInr: 2500, minSpend: 20000 },
  { cardId: "bob_eterna", rule: "≥₹40,000 per quarter for lounge", rewardMr: 0, rewardInr: 2500, minSpend: 13333 },
  { cardId: "hsbc_live_plus", rule: "Shared 10% accel cap ₹1,200/mo (~₹12k dining/food/grocery/utility/shopping)", rewardMr: 0, rewardInr: 1200, minSpend: 12000 },
];

export function getCardById(id: string): Card | undefined {
  return CARDS.find((c) => c.id === id);
}
